### ISSUE TITLE
Add In-Memory Cache

### ISSUE THREAD

**Issue by derekperkins** [qedus/nds#26]
I was remembering David Symond's talk on high performance apps and I went back and revisited it, and this slide popped out at me.
http://talks.golang.org/2013/highperf.slide#19

He shows memcache being 20x faster than datastore, and RAM 1000x faster than memcache. That got me thinking that it might be fantastic to add an in-memory cache option to nds. I'm thinking that you would initialize nds in the Init and provide a fixed memory size. Maybe I'm willing to allocate 5% of the total instance memory to this extra cache layer. Then any datastore lookup would first check RAM, then memcache and then finally datastore. If nds isn't ever initialized with a RAM cache, there would be no difference in how it functions.

I found this package earlier today that looks like it should handle all the heavy lifting of promoting and expiring cache items. Since it's from CloudFlare, I trust that it is highly performant and well coded, especially looking at their benchmarks.
http://godoc.org/github.com/cloudflare/golibs/lrucache

This is obviously isn't a must-have, nds has already made huge strides for us. I wanted to toss the idea out for future development. What are your thoughts?

**Comment by derekperkins** [comment]
I was thinking about this again and ran across https://github.com/golang/groupcache/. Using this as the backend for the in-memory cache removes the consistency issue while still providing the speed of having hot data stored in RAM.

**Comment by jongillham** [comment]
`groupcache` is awesome but it doesn't offer operations like `Delete` and `Set` making it impossible to maintain consistency. However with the new `context.Context` I am open to having a simple memory context and document that it would not maintain cache consistency.

**Comment by jongillham** [comment]
Closing this because it will likely make more sense to have a the `nds` package wrapped in a custom memory cache than add the option here.
