### ISSUE TITLE
script to install current Go SDK

### ISSUE THREAD

**Issue by stephanos** [qedus/nds#27]
I recently had the problem that each time the Go SDK version was changed my Travis build script wouldn't work anymore until I manually upgraded it to the latest version. Since then I wrote a small script to automatically pull the latest, correct Go SDK. If you accept that it might break anytime (since the URL is not officially documented), it might be interesting to you: https://gist.github.com/stephanos/d48fd3500614bd83e63e.

Cheers! :)

**Comment by derekperkins** [comment]
FYI, I turned that into a little redirect script that I use in my CI. http://sdkversion.appspot.com/ just redirects to the most recent version of the Linux 64bit Go SDK.

**Comment by jongillham** [comment]
I saw that a while back on Google Groups and actually used it in another project. Great idea! The .travis.yml config needs to be changed to support it so I will leave this issue open until it gets changed.

**Comment by jongillham** [comment]
Now uses http://sdkversion.appspot.com with commit 981972a07709438b2c2ebc745048e41884f81c30.
