### ISSUE TITLE
customize memcache expiration

### ISSUE THREAD

**Issue by stephanos** [qedus/nds#29]
I'm about to integrate my [hrd](https://github.com/101loops/hrd) library with nds and noticed that it is currently not possible to specify a custom memcache expiration time. 

Is this something you think might be worthwhile?

**Comment by jayp** [comment]
A max expiration would eventually self-heal #31 and #33. Otherwise, stale results can handarojnd forever if not changed/evicted.

I think it makes sense.

**Comment by jongillham** [comment]
You are correct, issues #31 and #33 would eventually heal. However, here's why I don't think adding a max expiration adds value for the majority of cases:

- Memcache doesn't stay around permanently. An entry can stay for days, maybe even weeks but it always gets evicted at some point in the future. Although I have to say there are no guarantees without specifying an eviction time.
- I can't think of a case where someone would expect strong cache consistency but be fine with that failing. Most people either want guaranteed cache consistency (which you get with using only nds.Get and nds.Put) or can tolerate not having it.
- Adding an extra setting increases complexity when there may only be a handful of uses.

**Comment by jayp** [comment]
Reason #2 resonates with me the most. That's really why this a forced expiration approach would be a hack.

With that said, for those that would like to deploy this hack: a forced reload every X minutes (or whatever), the extra setting would help. We could set it as an optional parameter, so no additional complexity for anyone who doesn't want to use it.
