### ISSUE TITLE
Support Managed VMs

### ISSUE THREAD

**Issue by stephanos** [qedus/nds#34]
Since App Engine will probably move more and more towards [Managed VMs](https://cloud.google.com/appengine/docs/managed-vms/) (currently beta) it might be a good idea to support both platforms, vanilla App Engine and Managed VMs.

*Note: The problem is that the import path has changed, "appengine" becomes "google.golang.org/appengine", see [related forum discussion](https://groups.google.com/forum/#!topic/google-appengine-go/2H76GkWRneI).*

**Comment by christopherhesse** [comment]
I have a preliminary version here: https://github.com/christopherhesse/nds

Converted with an automated tool (strings.Replace) plus a few changes for the property lists.

**Comment by jongillham** [comment]
Amazing! I've been meaning to do this for a long time but don't use Managed VMs. Can you think of any way to make the tests run?

**Comment by derekperkins** [comment]
David Symonds just posted this to the App Engine Group yesterday, so it doesn't look like testing will be available for Managed VMs quite yet. We're planning on migrating to the new context however, so we'll have to use the Managed VM package, even though we're still running on standard App Engine.
```
aetest is much harder to implement for Managed VMs, but there's no
reason why we can't make a thin wrapper for classic App Engine right
now to support your use case. I'll look into that next week.
```

**Comment by christopherhesse** [comment]
Yeah, looks like you can now use the managed vm imports from normal appengine: https://groups.google.com/forum/#!topic/app-engine-managed-vms/wtPReB-wdG8 so if I fix up my branch, I don't need to duplicate all the files probably.

**Comment by jongillham** [comment]
I just noticed your comment! That's great news. I guess we wait until there is an `aetest` for the new `google.golang.org/appengine` package?

On a different note, I almost got caught out with the API as it is and thinking I was in a transaction. I am therefore considering changing the API. What do you all think? https://github.com/qedus/nds/issues/37

**Comment by derekperkins** [comment]
I'm waiting for `aetest` before making any switches, so this isn't going to hold me back until then.

**Comment by derekperkins** [comment]
Is this going to split into two repos / parallel structs or will you be able to use the proper imports based on build tags?

**Comment by jongillham** [comment]
I hope to use the same `qedus/nds` package with build tags. I think that would be the cleanest.

**Comment by jongillham** [comment]
An initial commit is on this branch https://github.com/qedus/nds/tree/managedvm. I managed to get `aetest` to work with a little hach (https://github.com/qedus/nds/blob/managedvm/nds_test.go#L24). Using `context.Context` will also fix issue #37 without having to make an API change.

**Comment by jongillham** [comment]
Anyone got any issues with me promoting this to the master branch?

**Comment by derekperkins** [comment]
Do you have any idea how many people are using `nds`? We haven't migrated to using the new `context.Context` yet, though I can trivially support it for this use case in the meantime once this goes to master. It's a pretty major breaking change though for anyone not following these issues.

**Comment by jongillham** [comment]
No idea about how many people are using the package . It gets on average about 20 clones a day. I won't rush to promote anything to master as there are few more improvements I want to make, including the `PutCacheMulti` function – which again I have run into difficulties with.

**Comment by derekperkins** [comment]
My guess is that at least over the last month, a pretty significant portion of those 20 clones a day has been from our CI.

**Comment by derekperkins** [comment]
I just transitioned our codebase to the new Context package yesterday and it was surprisingly easy. I still left it embedded in our custom Context though. Anyhow, I think this issue can be closed.
