### ISSUE TITLE
memcache: server error

### ISSUE THREAD

**Issue by derekperkins** [qedus/nds#35]
We just had this show up in our logs from nds. `memcache: server error` Any idea what might be causing that?

**Comment by josephbergevin** [comment]
Looks like this may be tied to having special characters in the key. I had a question mark `?` and equals `=` in it originally when it was throwing the `memcache: server error`. I took those out, it worked just fine.

**Comment by jongillham** [comment]
@josephbergevin that's interesting to know, however I don't think this is an issue affecting NDS. The memcache keys will never use those [characters](https://github.com/qedus/nds/blob/master/nds.go#L157). [`datastore.Key.Encode()`](https://code.google.com/p/appengine-go/source/browse/appengine/datastore/key.go#211) uses base 64 encoding and removes the trailing "=". This is identical to what [Python's ndb does](https://code.google.com/p/appengine-ndb-experiment/source/browse/ndb/key.py#513).

@derekperkins are you still seeing these problems consistently? Could it have been that the API was down at the time?

**Comment by derekperkins** [comment]
@jongillham I actually work in the same room as @josephbergevin, so yes, I'm seeing the same error. :) I think Joe narrowed the problem down to the length of the `StringID`.

**Comment by josephbergevin** [comment]
I investigated further and it seems the error may be tied to a character limit. 147 chars is the max limit I could use in a key. If I go over that, I get these errors/warnings:
`GetMulti` gives a warning: `nds:lockMemcache AddMulti memcache: server error`
`PutMulti` throws an error: `memcache: server error`

**Comment by jongillham** [comment]
@josephbergevin awesome deductive work! I see the Python and Go SDK functionality differs here. The max key size on both platforms is 250 bytes. However Python automatically [hashes the key](https://cloud.google.com/appengine/docs/python/memcache/#Python_Limits) if it is longer than 250 bytes and Go [just raises an error](https://cloud.google.com/appengine/docs/go/memcache/#Go_Limits). 

This error must be what you are seeing. I'll investigate what type of hashing Python does and then copy it. I suppose there will be risk of hash collision but it must be small enough for the guys that made the Python SDK to not worry about.

What do you think?

**Comment by jongillham** [comment]
Just for reference [here's what Python's API does](https://code.google.com/p/googleappengine/source/browse/trunk/python/google/appengine/api/memcache/__init__.py#174).

    MAX_KEY_SIZE = 250
    
    if len(server_key) > MAX_KEY_SIZE:
        server_key = hashlib.sha1(server_key).hexdigest()
    
I wonder if it is worth using sha256 or sha512 to reduce the possibility of collisions?

**Comment by derekperkins** [comment]
Yeah, probably not. For it to be an issue, all of these would have to be the case:
 1. The 2 `StringID`s would have to hash to the same key
 1. Both of the total keys have to exceed 250 characters
 1. Both would have to be called in close enough proximity that neither one has been evicted from memcache already.

If it were more persistent data, it might be more of an issue, but I don't forsee this being that big of an issue.

**Comment by josephbergevin** [comment]
Yes, I agree with @derekperkins. That sounds great.

**Comment by jongillham** [comment]
Commit 924699ee6591412aaebdad297f96a738171543cd should hopefully fix this issue. I'll await feedback before I close this.

**Comment by josephbergevin** [comment]
That worked! I think you can go ahead and close the issue. Thanks for the quick responses!
