### ISSUE TITLE
Failing tests with "appengine: NewContext passed an unknown http.Request"

### ISSUE THREAD

**Issue by johngb** [qedus/nds#41]
When trying to run the tests using `goapp test -v ./...` I get the following error:

> appengine: NewContext passed an unknown http.Request

I'm assuming this is due to the unspecified `*http.Request` given in https://github.com/qedus/nds/blob/master/nds_test.go#L31

**Comment by jongillham** [comment]
I can't recreate this. I just updated to the latest SDK (https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_darwin_amd64-1.9.23.zip) to check and `goapp test -v ./...` works. (I had to delete the contents of the `pkg` directory before the tests would run as I had been using 1.9.21 previously.)

The reason for doing `c.Request().(*http.Request))` is to get a 'known' request as it already has a context associated with it. What version of App Engine SDK are you using?

**Comment by johngb** [comment]
@jongillham I am using version 1.9.23, and have been for a while.  But your suggestion of clearing the `pkg` directory got things working, and the tests are now passing, so I'll close this issue.

One unrelated thought, is that the tests take a long time to run, mostly because the python devappserver is quite slow in starting up.  If you don't rely on previous states for your tests and load the data for each test before the test, you can use a single context for all tests.  I had a case where my tests were taking about 5 minutes to run, and by doing this got it down to about 9 seconds.
