### ISSUE TITLE
Migrating data when the underlying struct changes

### ISSUE THREAD

**Issue by kidoman** [qedus/nds#47]
We have to now put on the big boy pants and start migrating some data which is already present in datastore. The struct has since then changed: a few columns added (which is not a problem) and some columns removed (which is a problem).

When trying to load such an entity from datastore (via nds; to keep the cache consistent) we will end up with an error.

Any recommendations on how to go about this?

**Comment by mzimmerman** [comment]
When I have to do this I write a one time migration function.  Read in the
old structs, write out the new ones in their place.

You can also ignore that error and your data will still be there.

**Comment by jongillham** [comment]
As @mzimmerman says it is usually best to create a specific function and use that. If you can't afford to stop user access to the datastore while the migration is happening then it is advisable to change your code that reads the datastore entity to be migrated to be able to read both types of entity. Once the migration is complete then just remove the old code.

Memcache errors generated by nds also don't matter if you only see them in the logs. They won't compromise integrity. If they do matter and will compromise integrity then they will automatically bubble up to produce an error in the API.
