### ISSUE TITLE
nds item not stored warning

### ISSUE THREAD

**Issue by johngb** [qedus/nds#49]
In production on a low load service, I'm getting the following error about once a day:

`nds:lockMemcache AddMulti memcache: item not stored`

My understanding is that is't simply a case of saving to memcache failing, in which case it only means that the next Get would have to get the contents from the datastore instead of memcache.

If this is indeed the case, please close this issue, but on the offchance that my understanding is incorrect, I thought it would be useful to have a record.

**Comment by jongillham** [comment]
Your understanding is correct. It's usually the result of an expiry of some item. This won't affect consistency or entity persistence and you can safely ignore it. If these errors appear really frequently it probably means there has been a forced purge of your data by Google or the memcache API is having trouble. They usually resolve in minutes. You don't need to do anything.

If any memcache error would affect consistency then it will be bubbled up in the form of an `error` by the API. Such is the case for example when attempting to delete an entity and nds is not able to get confirmation from memcache that the memcache item has also been deleted.

**Comment by jongillham** [comment]
Your understanding is correct. It's usually the result of an expiry of some item. This won't affect consistency or entity persistence and you can safely ignore it. If these errors appear really frequently it probably means there has been a forced purge of your data by Google or the memcache API is having trouble. They usually resolve in minutes. You don't need to do anything.

If any memcache error would affect consistency then it will be bubbled up in the form of an `error` by the API. Such is the case for example when attempting to delete an entity and nds is not able to get confirmation from memcache that the memcache item has also been deleted.

**Comment by johngb** [comment]
Thanks @jongillham.  In a related question, based on your experience, do you know if these sorts of warnings are less common with the paid memcache service vs. the free on?

**Comment by jongillham** [comment]
Sorry I don't know. The free tier has always been adequate for my apps. You could have a go for a couple of days and see what happens.
