### ISSUE TITLE
Panic with datastore.PropertyLoadSaver

### ISSUE THREAD

**Issue by tim-lebedkov** [qedus/nds#52]
I get a panic with the stack trace shown below with "nds". It seems that "x*Record" is nil in "Load"

====================================
// Lädt einen Datensatz aus dem Datastore
func (x *Record) Load(ps []datastore.Property) error {
	x.props = make([]datastore.Property, 0, len(ps)) <============== line storage.go:165
	x.Created = time.Now()
	x.Modified = x.Created
....

=================================
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x47b88a]

goroutine 31 [running]:
panic(0x8ff760, 0xc82000a070)
	/home/tim/Dokumente/go_appengine/goroot/src/runtime/panic.go:481 +0x3e6
main66787.(*Record).Load(0x0, 0xc820285c70, 0x5, 0x5, 0x0, 0x0)
	storage.go:165 +0x75a
github.com/qedus/nds.setValue(0x944b20, 0xc8201e23a0, 0x196, 0xc820285c70, 0x5, 0x5, 0x0, 0x0)
	/home/tim/Dokumente/gopath/src/github.com/qedus/nds/nds.go:155 +0x1e4
github.com/qedus/nds.loadDatastore(0x7f81cd1d36e8, 0xc820270ae0, 0xc8201df720, 0x1, 0x1, 0x7f81cd1cf0a8, 0x800d60, 0x0, 0x0)
	/home/tim/Dokumente/gopath/src/github.com/qedus/nds/get.go:339 +0x5c7
github.com/qedus/nds.getMulti(0x7f81cd1d36e8, 0xc820270ae0, 0xc8202424d0, 0x1, 0x15, 0x800d60, 0xc820273340, 0x97, 0x0, 0x0)
	/home/tim/Dokumente/gopath/src/github.com/qedus/nds/get.go:164 +0x3cf
github.com/qedus/nds.GetMulti.func1(0x7f81cd1d36e8, 0xc820270ae0, 0xc8202768d0, 0x1, 0x1, 0xc8202768e0, 0x0, 0xc8202424d0, 0x1, 0x15, ...)
	/home/tim/Dokumente/gopath/src/github.com/qedus/nds/get.go:78 +0x19c
created by github.com/qedus/nds.GetMulti
	/home/tim/Dokumente/gopath/src/github.com/qedus/nds/get.go:81 +0x32b

**Comment by jongillham** [comment]
Thanks for the bug report. I'll provide a fix if this is not what `datastore` also does.

**Comment by jongillham** [comment]
Hi @tim-lebedkov can you see if the code in branch https://github.com/qedus/nds/tree/issue-52 fixes your issue? If it does then I'll merge it into master.

**Comment by tim-lebedkov** [comment]
The fix works. Thank you!
