### ISSUE TITLE
Make compatible with cloud.google.com/go

### ISSUE THREAD

**Issue by jongillham** [qedus/nds#54]
For this to happen cloud.google.com/go needs to be compatible with App Engine Standard and the memcache package needs to be implemented.

**Comment by newlix** [comment]
Will this change support nds be used outside the App Engine environment? Because I am currently using grpc which is not yet supported by App Engine .

**Comment by jongillham** [comment]
Yes once supporting cloud.google.com/go it should be possible for nds to be used outside App Engine. However looking at the cloud.google.com/go/datastore API I see it is quite different to the google.golang.org/appengine/datastore one. Therefore the current nds API will probably have to be deprecated and replaced by one similar to the cloud.google.com/go/datastore one.

**Comment by someone1** [comment]
Just an FYI - The alpha Memcache API is said to access the same data whether accessed via AppEngine Standard or Flexible (presumably, it'll be accessible outside of GCP as the other new APIs are too and use gRPC).

That aside, there is a recommendation for using redis labs or other caching services from now until the Memcache API becomes available. Does it make sense to re-architect nds to interface with the new datastore package and use a pluggable caching interface? This way users can switch to their own caching service if they so choose to though I'd imagine mostly everybody would opt to use Google's Memcache API when it becomes available.

Just an idea - this can technically start now and the package can then only support AppEngine Standard until new caching plugins are built out.

I've already had to migrate away from nds as I require a Flexible VM and already feel/see a performance penalty as a result, hoping to switch back ASAP.

**Comment by jongillham** [comment]
@someone1 thanks for the notification about Memcache API. I am really looking forward to it arriving, as using the Flexible VM without it gets expensive.

Being able to plug in a different caching layer does make sense. However I am in two minds as to whether I would want to add that complexity to `nds`. This is only because I imagine it is probably simpler and more flexible for users of the `datastore` package to compose their own solutions as they see fit.

My current plan is to completely replicate all the `https://godoc.org/cloud.google.com/go/datastore.Client` functions with an `nds.Client` struct (not interface) and do no more for in the name of simplicity. It would have been nice if `datastore.Client` was an interface but I am sure there is a good reason why it isn't. However as I said, I am in two minds so will probably try a few different iterations before I settle on something. If the new memcache has the same properties as the old on then it should hopefully be a straight forward port.

**Comment by someone1** [comment]
Not sure if this is the official memcache replacement, but maybe implementing a pluggable caching mechanism would be the way to go here: https://cloud.google.com/memorystore/ (looks like the cache is NOT shared between flexible/standard and this new service is only accessible via flexible)

The new [datastore package](https://godoc.org/cloud.google.com/go/datastore) is more robust than the appengine one, allowing nested structs and mutations - I've switched to this package even on AppEngine Standard deployments due to the increased feature set. I would really like caching though and believe this package to be the perfect candidate to morph into that solution.

**Comment by jongillham** [comment]
Thanks for the info. Yes it does look like memorystore is a likely candidate. It’ll be interesting to see how similar it’s consistency guarantees are to memcache’s.

**Comment by someone1** [comment]
Ok to close this issue?

**Comment by jongillham** [comment]
Definitely! Amazing work @someone1 !
