### ISSUE TITLE
ErrFieldMismatch in GetMulti returns only one result

### ISSUE THREAD

**Issue by yonida** [qedus/nds#55]
When using `GetMulti`, if there is a difference between datastore and the struct used to load the data into, datastore returns the data, with an error type `ErrFieldMismatch` - `cannot load field "X" into a "Y": no such struct field`.
The result from nds for N structs that trigger this error, is only a single populated struct, and N-1 empty structs (no fields populated), with N errors.
It should be all the structs with their values, and N errors.

I believe that this can be fixed by changing https://github.com/qedus/nds/blob/master/get.go#L359 to `cacheItems[index].err = err`
I can provide a PR if needed.

**Comment by jongillham** [comment]
Thanks for the report. It would be great if you could submit a PR with a unit test.

**Comment by jongillham** [comment]
The unit test could have the datastore and nds functionality compared side by side to show they are equal.

**Comment by yonida** [comment]
Here you go
https://github.com/qedus/nds/pull/56

**Comment by jongillham** [comment]
Fixed with commit 8d3030236f1a7740dc3bbab6b3239bb79785f999.
