### ISSUE TITLE
Tag v2 branch as v2.0.0

### ISSUE THREAD

**Issue by someone1** [qedus/nds#63]
Trying to get this to work on a go1.10 project and I think the release needs to be tagged to work.

**Comment by jongillham** [comment]
I've just tagged v2.0.0. Let me know if it works.

**Comment by someone1** [comment]
Hmmm - doesn't seem to be making a difference... 

My apologies, I thought from the documentation that would be enough but it doesn't appear so.

**Comment by someone1** [comment]
Closing as I don't think there's an easy solution to support those who aren't using Go Modules (will becomes the default soon anyway)
